version: 2.1
jobs:
  unit-test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm test
  staging-deploy:
    machine: true
    steps:
      - checkout
      - run: /bin/sh ci/deploy
      - run: /bin/sh ci/release

workflows:
  version: 2
  crypto-shop-pipeline:
    jobs:
      - unit-test
      - staging-deploy:
        requires:
          - unit-test
