version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: NODE_ENV=production npm run build && npm run export
      - save_cache:
          key: build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - out
  unit-test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm test
  staging-deploy:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: ./ci/deploy
      - run: ./ci/release

workflows:
  version: 2
  crypto-shop-pipeline:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - staging-deploy:
          requires:
            - unit-test
